//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ejercicioWebServices.ConversionMoneda {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/", ConfigurationName="ConversionMoneda.NumberConversionSoapType")]
    public interface NumberConversionSoapType {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento NumberToWordsResult del espacio de nombres http://www.dataaccess.com/webservicesserver/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ejercicioWebServices.ConversionMoneda.NumberToWordsResponse NumberToWords(ejercicioWebServices.ConversionMoneda.NumberToWordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ejercicioWebServices.ConversionMoneda.NumberToWordsResponse> NumberToWordsAsync(ejercicioWebServices.ConversionMoneda.NumberToWordsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento NumberToDollarsResult del espacio de nombres http://www.dataaccess.com/webservicesserver/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ejercicioWebServices.ConversionMoneda.NumberToDollarsResponse NumberToDollars(ejercicioWebServices.ConversionMoneda.NumberToDollarsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ejercicioWebServices.ConversionMoneda.NumberToDollarsResponse> NumberToDollarsAsync(ejercicioWebServices.ConversionMoneda.NumberToDollarsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NumberToWordsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberToWords", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ejercicioWebServices.ConversionMoneda.NumberToWordsRequestBody Body;
        
        public NumberToWordsRequest() {
        }
        
        public NumberToWordsRequest(ejercicioWebServices.ConversionMoneda.NumberToWordsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class NumberToWordsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ulong ubiNum;
        
        public NumberToWordsRequestBody() {
        }
        
        public NumberToWordsRequestBody(ulong ubiNum) {
            this.ubiNum = ubiNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NumberToWordsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberToWordsResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ejercicioWebServices.ConversionMoneda.NumberToWordsResponseBody Body;
        
        public NumberToWordsResponse() {
        }
        
        public NumberToWordsResponse(ejercicioWebServices.ConversionMoneda.NumberToWordsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class NumberToWordsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NumberToWordsResult;
        
        public NumberToWordsResponseBody() {
        }
        
        public NumberToWordsResponseBody(string NumberToWordsResult) {
            this.NumberToWordsResult = NumberToWordsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NumberToDollarsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberToDollars", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ejercicioWebServices.ConversionMoneda.NumberToDollarsRequestBody Body;
        
        public NumberToDollarsRequest() {
        }
        
        public NumberToDollarsRequest(ejercicioWebServices.ConversionMoneda.NumberToDollarsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class NumberToDollarsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal dNum;
        
        public NumberToDollarsRequestBody() {
        }
        
        public NumberToDollarsRequestBody(decimal dNum) {
            this.dNum = dNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NumberToDollarsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberToDollarsResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ejercicioWebServices.ConversionMoneda.NumberToDollarsResponseBody Body;
        
        public NumberToDollarsResponse() {
        }
        
        public NumberToDollarsResponse(ejercicioWebServices.ConversionMoneda.NumberToDollarsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class NumberToDollarsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NumberToDollarsResult;
        
        public NumberToDollarsResponseBody() {
        }
        
        public NumberToDollarsResponseBody(string NumberToDollarsResult) {
            this.NumberToDollarsResult = NumberToDollarsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NumberConversionSoapTypeChannel : ejercicioWebServices.ConversionMoneda.NumberConversionSoapType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NumberConversionSoapTypeClient : System.ServiceModel.ClientBase<ejercicioWebServices.ConversionMoneda.NumberConversionSoapType>, ejercicioWebServices.ConversionMoneda.NumberConversionSoapType {
        
        public NumberConversionSoapTypeClient() {
        }
        
        public NumberConversionSoapTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NumberConversionSoapTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumberConversionSoapTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumberConversionSoapTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ejercicioWebServices.ConversionMoneda.NumberToWordsResponse ejercicioWebServices.ConversionMoneda.NumberConversionSoapType.NumberToWords(ejercicioWebServices.ConversionMoneda.NumberToWordsRequest request) {
            return base.Channel.NumberToWords(request);
        }
        
        public string NumberToWords(ulong ubiNum) {
            ejercicioWebServices.ConversionMoneda.NumberToWordsRequest inValue = new ejercicioWebServices.ConversionMoneda.NumberToWordsRequest();
            inValue.Body = new ejercicioWebServices.ConversionMoneda.NumberToWordsRequestBody();
            inValue.Body.ubiNum = ubiNum;
            ejercicioWebServices.ConversionMoneda.NumberToWordsResponse retVal = ((ejercicioWebServices.ConversionMoneda.NumberConversionSoapType)(this)).NumberToWords(inValue);
            return retVal.Body.NumberToWordsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ejercicioWebServices.ConversionMoneda.NumberToWordsResponse> ejercicioWebServices.ConversionMoneda.NumberConversionSoapType.NumberToWordsAsync(ejercicioWebServices.ConversionMoneda.NumberToWordsRequest request) {
            return base.Channel.NumberToWordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ejercicioWebServices.ConversionMoneda.NumberToWordsResponse> NumberToWordsAsync(ulong ubiNum) {
            ejercicioWebServices.ConversionMoneda.NumberToWordsRequest inValue = new ejercicioWebServices.ConversionMoneda.NumberToWordsRequest();
            inValue.Body = new ejercicioWebServices.ConversionMoneda.NumberToWordsRequestBody();
            inValue.Body.ubiNum = ubiNum;
            return ((ejercicioWebServices.ConversionMoneda.NumberConversionSoapType)(this)).NumberToWordsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ejercicioWebServices.ConversionMoneda.NumberToDollarsResponse ejercicioWebServices.ConversionMoneda.NumberConversionSoapType.NumberToDollars(ejercicioWebServices.ConversionMoneda.NumberToDollarsRequest request) {
            return base.Channel.NumberToDollars(request);
        }
        
        public string NumberToDollars(decimal dNum) {
            ejercicioWebServices.ConversionMoneda.NumberToDollarsRequest inValue = new ejercicioWebServices.ConversionMoneda.NumberToDollarsRequest();
            inValue.Body = new ejercicioWebServices.ConversionMoneda.NumberToDollarsRequestBody();
            inValue.Body.dNum = dNum;
            ejercicioWebServices.ConversionMoneda.NumberToDollarsResponse retVal = ((ejercicioWebServices.ConversionMoneda.NumberConversionSoapType)(this)).NumberToDollars(inValue);
            return retVal.Body.NumberToDollarsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ejercicioWebServices.ConversionMoneda.NumberToDollarsResponse> ejercicioWebServices.ConversionMoneda.NumberConversionSoapType.NumberToDollarsAsync(ejercicioWebServices.ConversionMoneda.NumberToDollarsRequest request) {
            return base.Channel.NumberToDollarsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ejercicioWebServices.ConversionMoneda.NumberToDollarsResponse> NumberToDollarsAsync(decimal dNum) {
            ejercicioWebServices.ConversionMoneda.NumberToDollarsRequest inValue = new ejercicioWebServices.ConversionMoneda.NumberToDollarsRequest();
            inValue.Body = new ejercicioWebServices.ConversionMoneda.NumberToDollarsRequestBody();
            inValue.Body.dNum = dNum;
            return ((ejercicioWebServices.ConversionMoneda.NumberConversionSoapType)(this)).NumberToDollarsAsync(inValue);
        }
    }
}
